/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* To-do
- Errorproofing
- Making frames look nice
- Some additional stuff
- Warning pop-up on close
- Clear button
*/

package my.employeedatabase;

import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.table.*;

/**
 *
 * @author shawnzhang12
 */
public class EmployeeDatabaseUI extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeDatabaseUI
     */
    MyEmployeeDatabase theEmployeeDatabase = new MyEmployeeDatabase(10);
    EmployeeInfo genericEmployee = new EmployeeInfo();
    FullTimeEmployee fullEmployee = new FullTimeEmployee(); 
    PartTimeEmployee partEmployee = new PartTimeEmployee();
    File file = new File("src/data/employeedatabase.txt");

    Dimension maxScreenSize = Toolkit.getDefaultToolkit().getScreenSize();
    int height = maxScreenSize.height * 2 / 3;
    int width = maxScreenSize.width * 1 / 2;
    Dimension windowSize = new Dimension(width, height);
    
    boolean editMode = false;

    public EmployeeDatabaseUI() {
        initComponents();
        
        //Sets the size of frames, since Netbeans defaults act weirdly
        this.setSize(windowSize);
        jFrame1.setSize(new Dimension(width * 3/4, height / 3));
        jFrame3.setSize(new Dimension(666, height * 1/6));
        jFrame4.setSize(new Dimension(width * 3/5, height * 3/5 + 20));
        jPanel9.setSize(new Dimension(666, jPanel9.getHeight()));
         
        ArrayList<String> rawEmployeeList = new ArrayList<>();
        try {
            rawEmployeeList = theEmployeeDatabase.readFile(file);
        } catch (IOException e) {
            System.out.println("Error file not found. Creating file: " + e.getMessage());
            file.getParentFile().mkdirs();
        }

        for (int i = 0; i < rawEmployeeList.size(); i++) {
            if (rawEmployeeList.get(i).contains("%")) {
                String[] halves = rawEmployeeList.get(i).substring(1).split("%");
                if (rawEmployeeList.get(i).charAt(0) == '1') {
                    FullTimeEmployee anothaFullEmployee = new FullTimeEmployee(Integer.parseInt(halves[0]), halves[1], halves[2], Integer.parseInt(halves[3]), Integer.parseInt(halves[4]), Double.parseDouble(halves[5]), Double.parseDouble(halves[6]));
                    theEmployeeDatabase.addToTable(anothaFullEmployee);
                } else if (rawEmployeeList.get(i).charAt(0) == '0') {
                    PartTimeEmployee anothaPartEmployee = new PartTimeEmployee(Integer.parseInt(halves[0]), halves[1], halves[2], Integer.parseInt(halves[3]), Integer.parseInt(halves[4]), Double.parseDouble(halves[5]), Double.parseDouble(halves[6]), Double.parseDouble(halves[7]), Double.parseDouble(halves[8]));
                    theEmployeeDatabase.addToTable(anothaPartEmployee);
                }
            }
        }
        jPanel9.setVisible(false);
        jLabel24.setVisible(false);
        jLabel25.setVisible(false);
    }
    public void clearMainFrame(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField10.setText("");
        buttonGroup2.clearSelection();
        jComboBox1.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jFrame3 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jFrame4 = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        jButton13 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        jFrame1.setLocation(new java.awt.Point(0, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee Number", "First Name", "Last Name", "Full Time/Part Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton12.setText("Edit");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jButton15.setText("Remove");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        jButton16.setText("Close");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jButton12)
                .addGap(97, 97, 97)
                .addComponent(jButton15)
                .addGap(96, 96, 96)
                .addComponent(jButton16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton15)
                    .addComponent(jButton16))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Shonar Bangla", 1, 36)); // NOI18N
        jLabel8.setText("Welcome to the Employee Database!");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/employeedatabase/newpackage/Gold.png"))); // NOI18N
        jLabel9.setOpaque(true);

        jButton8.setText("Enter");

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel8))
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jButton8)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jFrame3.setResizable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel4.setMinimumSize(new java.awt.Dimension(666, 68));
        jPanel4.setPreferredSize(new java.awt.Dimension(666, 68));

        jLabel5.setText("Enter Employee Number Here:");

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton17.setText("Close");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });

        jComboBox2.setEditable(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addGap(33, 33, 33)
                .addComponent(jButton17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox2, jTextField9});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 656, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 274, Short.MAX_VALUE))
        );

        jLabel17.setText("The employee \"000000 has been removed\" ");

        jButton11.setText("OK");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel17)
                    .addComponent(jButton11))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addGap(35, 35, 35))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel13.setText("Name");

        jLabel18.setText("Sex");

        jLabel19.setText("Full/Part Time");

        jLabel20.setText("Gross Annual Cost");

        jLabel21.setText("Work Location");

        jLabel22.setText("EmployeeNumber");

        jTextPane2.setFocusable(false);
        jScrollPane3.setViewportView(jTextPane2);

        jTextPane3.setFocusable(false);
        jScrollPane4.setViewportView(jTextPane3);

        jTextPane4.setFocusable(false);
        jScrollPane5.setViewportView(jTextPane4);

        jTextPane5.setFocusable(false);
        jScrollPane6.setViewportView(jTextPane5);

        jTextPane6.setFocusable(false);
        jScrollPane7.setViewportView(jTextPane6);

        jTextPane7.setFocusable(false);
        jScrollPane8.setViewportView(jTextPane7);

        jLabel23.setText("Net Annual Cost");

        jTextPane8.setFocusable(false);
        jScrollPane9.setViewportView(jTextPane8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addComponent(jScrollPane3))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(28, 28, 28))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel23))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        jButton13.setText("Edit");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        jButton7.setText("Remove");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton14.setText("Close");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame4Layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(jButton13)
                    .addGap(69, 69, 69)
                    .addComponent(jButton7)
                    .addGap(76, 76, 76)
                    .addComponent(jButton14)
                    .addContainerGap(111, Short.MAX_VALUE)))
        );

        jFrame4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton13, jButton14, jButton7});

        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
            .addGroup(jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame4Layout.createSequentialGroup()
                    .addContainerGap(326, Short.MAX_VALUE)
                    .addGroup(jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton13)
                        .addComponent(jButton7)
                        .addComponent(jButton14))
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Employee Number:");

        jLabel4.setText("Sex:");

        jLabel10.setText("Work Location:");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Male");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Female");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("Other");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mississauga", "Ottawa", "Toronto" }));

        jLabel6.setText("Employment Status:");

        jButton9.setText("Full Time");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setText("Part Time");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton5))
                            .addComponent(jButton9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButton10))
                            .addComponent(jRadioButton6))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField1, jTextField2, jTextField3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField1, jTextField3});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controls", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jButton1.setText("Add");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton3.setText("Search");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Display");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton6.setText("Save");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton3, jButton4});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton3, jButton4, jButton6});

        jButton5.setText("Close");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Full Time", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel7.setText("Salary:");

        jLabel11.setText("Deduction Rate:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jTextField4))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField4, jTextField5});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField4, jTextField5});

        jLayeredPane1.add(jPanel5, "card2");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Part Time", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel12.setText("Hourly Wage:");

        jLabel14.setText("Hours per Week:");

        jLabel15.setText("Weeks per Year:");

        jLabel16.setText("Deduction Rate:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 301, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField10, jTextField6, jTextField7, jTextField8});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 78, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField10, jTextField6, jTextField7, jTextField8});

        jLayeredPane1.add(jPanel6, "card3");

        jLabel24.setText("jLabel24");

        jLabel25.setText("jLabel25");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // Adds or saves edits to an employee based on the state of the boolean "editMode"
        EmployeeInfo changingEmployee = theEmployeeDatabase.searchTable(genericEmployee.getEmployeeNumber()); // Only matters if "editMode" == true
            
        boolean check = true;
        if (jRadioButton4.isSelected() == true) {
            fullEmployee.setSex(0);
        } else if (jRadioButton5.isSelected() == true) {
            fullEmployee.setSex(1);
        } else if (jRadioButton6.isSelected() == true) {
            fullEmployee.setSex(2);
        } else {
            check = false;
        }

        if (jComboBox1.getSelectedItem().equals("Mississauga")) {
            fullEmployee.setWorkLocation(0);
        } else if (jComboBox1.getSelectedItem().equals("Toronto")) {
            fullEmployee.setWorkLocation(1);
        } else if (jComboBox1.getSelectedItem().equals("Ottawa")) {
            fullEmployee.setWorkLocation(2);
        } else {
            check = false;
        }

        if (jTextField1.getText().equals("") == true || jTextField2.getText().equals("") == true || jTextField3.getText().equals("") == true) {
            check = false;
        }

        if (check == true) {
            jLabel24.setVisible(false);
            if (jPanel5.isVisible()) {
                if (jTextField3.getText().matches("[0-9]*\\.?[0-9]*") && jTextField4.getText().matches("[0-9]*\\.?[0-9]*") && jTextField5.getText().matches("[0-9]*\\.?[0-9]*")) {
                    if (editMode == true){
                        FullTimeEmployee changingFullEmployee = (FullTimeEmployee) changingEmployee;
                        changingFullEmployee.setFirstName(jTextField1.getText());
                        changingFullEmployee.setLastName(jTextField2.getText());
                        changingFullEmployee.setEmployeeNumber(Integer.parseInt(jTextField3.getText()));
                        changingFullEmployee.setSex(fullEmployee.getSex());
                        changingFullEmployee.setWorkLocation(fullEmployee.getWorkLocation());
                        changingFullEmployee.setYearlySalary(Double.parseDouble(jTextField4.getText()));
                        changingFullEmployee.setDeductionsRate(Double.parseDouble(jTextField5.getText()));
                        theEmployeeDatabase.removeFromTable(genericEmployee.getEmployeeNumber());
                        theEmployeeDatabase.addToTable(changingFullEmployee);
                        editMode = false;
                        jButton1.setText("Add");
                    } else {
                        fullEmployee = new FullTimeEmployee(Integer.parseInt(jTextField3.getText()), jTextField1.getText(), jTextField2.getText(), fullEmployee.getSex(), fullEmployee.getWorkLocation(), Double.parseDouble(jTextField4.getText()), Double.parseDouble(jTextField5.getText()));
                        theEmployeeDatabase.addToTable(fullEmployee);
                    }
                    clearMainFrame();
                } else {
                    jLabel25.setVisible(true);
                }
            }
            if (jPanel6.isVisible()) {
                if (jTextField3.getText().matches("[0-9]*\\.?[0-9]*") && jTextField6.getText().matches("[0-9]*\\.?[0-9]*") && jTextField7.getText().matches("[0-9]*\\.?[0-9]*") && jTextField8.getText().matches("[0-9]*\\.?[0-9]*") && jTextField10.getText().matches("[0-9]*\\.?[0-9]*")) {
                    if (editMode == true){
                        PartTimeEmployee changingPartEmployee = (PartTimeEmployee) changingEmployee;
                        changingPartEmployee.setFirstName(jTextField1.getText());
                        changingPartEmployee.setLastName(jTextField2.getText());
                        changingPartEmployee.setEmployeeNumber(Integer.parseInt(jTextField3.getText()));
                        changingPartEmployee.setSex(fullEmployee.getSex());
                        changingPartEmployee.setWorkLocation(fullEmployee.getWorkLocation());
                        changingPartEmployee.setHourlyWage(Double.parseDouble(jTextField6.getText()));
                        changingPartEmployee.setHoursPerWeek(Double.parseDouble(jTextField7.getText())); 
                        changingPartEmployee.setWeeksPerYear(Double.parseDouble(jTextField8.getText()));
                        changingPartEmployee.setDeductionsRate(Double.parseDouble(jTextField10.getText()));
                        theEmployeeDatabase.removeFromTable(genericEmployee.getEmployeeNumber());
                        theEmployeeDatabase.addToTable(changingPartEmployee);
                        editMode = false;
                        jButton1.setText("Add");
                    } else {
                        partEmployee = new PartTimeEmployee(Integer.parseInt(jTextField3.getText()), jTextField1.getText(), jTextField2.getText(), fullEmployee.getSex(), fullEmployee.getWorkLocation(), Double.parseDouble(jTextField6.getText()), Double.parseDouble(jTextField7.getText()), Double.parseDouble(jTextField8.getText()), Double.parseDouble(jTextField10.getText()));
                        theEmployeeDatabase.addToTable(partEmployee);
                    }
                    clearMainFrame();
                } else {
                    jLabel25.setVisible(true);
                }
            }
        } else {
            jLabel24.setVisible(true);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // Prints out employees by EmployeeNumber. Headers can be clicked to sort by other parameters.
        ArrayList<EmployeeInfo> employeeList = theEmployeeDatabase.retrieveTable();
        
        //While jTable has a method to sort the table based on columns, it sorts based on strings not the integer values so this is necessary
        BinaryTree sortingTree = new BinaryTree();
        System.out.println(sortingTree.getNumInTree());
        
        
        for (int i = 0; i < employeeList.size();i++){
            sortingTree.addToTree(employeeList.get(0),employeeList.get(i));
        }
        employeeList.clear();
        sortingTree.inorder(sortingTree.getRoot(),employeeList);
        
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        tModel.setRowCount(employeeList.size());
        jTable1.setModel(tModel);
        jTable1.setAutoCreateRowSorter(true);
        for (int i = 0; i < employeeList.size(); i++) {
            jTable1.setValueAt(employeeList.get(i).getEmployeeNumber(), i, 0);
            jTable1.setValueAt(employeeList.get(i).getFirstName(), i, 1);
            jTable1.setValueAt(employeeList.get(i).getLastName(), i, 2);
            if (employeeList.get(i) instanceof my.employeedatabase.FullTimeEmployee) {
                jTable1.setValueAt("Full Time", i, 3);
            } else if (employeeList.get(i) instanceof my.employeedatabase.PartTimeEmployee) {
                jTable1.setValueAt("Part Time", i, 3);
            }
        }
        if (employeeList.size() < 8);
        jTable1.setSize(new Dimension(300, 128 - (8 - employeeList.size()) * 16));
        jFrame1.pack();
        jButton12.setVisible(false);
        jButton15.setVisible(false);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here: prepares the search window for use
        jTextPane2.setText("");
        jTextPane3.setText("");
        jTextPane4.setText("");
        jTextPane5.setText("");
        jTextPane6.setText("");
        jTextPane7.setText("");
        jTextPane8.setText("");
        jTextField9.setText("");
        
        jPanel9.setVisible(false);
        jButton13.setVisible(false);
        jButton7.setVisible(false);
        jButton14.setVisible(false);
        jFrame3.setVisible(true);
        
        jComboBox2.setEditable(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here: validation, colour code
        EmployeeInfo removedEmployee = theEmployeeDatabase.removeFromTable(Integer.parseInt(jTextField9.getText()));
        String msg = "";
        if (removedEmployee != null){
            msg = "The employee with employee number \"" + removedEmployee.getEmployeeNumber() + "\" was removed from our database";
        } else if (removedEmployee == null){
            msg = "The employee does not exist in our database";
        }
        
        jLabel17.setText(msg);
        jDialog1.pack();
        jDialog1.setVisible(true);
        jButton7.setVisible(false);
        jButton13.setVisible(false);
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        this.dispose();
        jFrame1.dispose();
        jFrame3.dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here: Activate full time, deactivate part time
        jPanel5.setVisible(true);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here: Activate part time, deactivate full time
        jPanel6.setVisible(true);
        jPanel5.setVisible(false);
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        try {
            theEmployeeDatabase.writeFile(file);
        } catch (IOException e) {
            System.out.println("Error: No file found" + e.getMessage());
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here: closes out display window
        jFrame4.dispose();
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        EmployeeInfo anEmployee = theEmployeeDatabase.searchTable(Integer.parseInt(jTextField9.getText()));
        if (anEmployee instanceof my.employeedatabase.FullTimeEmployee) {
            jPanel6.setVisible(false);
            jPanel5.setVisible(true);
            FullTimeEmployee eFull = (FullTimeEmployee) anEmployee;
            jTextPane6.setText("Part Time");
            jTextPane7.setText(Double.toString(eFull.calcAnnualGrossIncome()));
            jTextPane8.setText(Double.toString(eFull.calcAnnualNetIncome()));

            jTextField4.setText(Double.toString(eFull.getYearlySalary()));
            jTextField5.setText(Double.toString(eFull.getDeductionsRate()));
        } else if (anEmployee instanceof my.employeedatabase.PartTimeEmployee) {
            jPanel5.setVisible(false);
            jPanel6.setVisible(true);
            PartTimeEmployee ePart = (PartTimeEmployee) anEmployee;
            jTextPane6.setText("Full Time");
            jTextPane7.setText(Double.toString(ePart.calcAnnualGrossIncome()));
            jTextPane8.setText(Double.toString(ePart.calcAnnualNetIncome()));

            jTextField6.setText(Double.toString(ePart.getHourlyWage()));
            jTextField7.setText(Double.toString(ePart.getHoursPerWeek()));
            jTextField8.setText(Double.toString(ePart.getWeeksPerYear()));
            jTextField10.setText(Double.toString(ePart.getDeductionsRate()));
        }

        jTextPane2.setText(anEmployee.getFirstName() + " " + anEmployee.getLastName());
        jTextPane3.setText(Integer.toString(anEmployee.getEmployeeNumber()));
        if (anEmployee.getSex() == 0) {
            jTextPane4.setText("Male");
        } else if (anEmployee.getSex() == 1) {
            jTextPane4.setText("Female");
        } else if (anEmployee.getSex() == 2) {
            jTextPane4.setText("Non-Binary");
        }
        if (anEmployee.getWorkLocation() == 0) {
            jTextPane5.setText("Mississauga");
        } else if (anEmployee.getWorkLocation() == 1) {
            jTextPane5.setText("Toronto");
        } else if (anEmployee.getWorkLocation() == 2) {
            jTextPane5.setText("Ottawa");
        }

        jTextField3.setText(Integer.toString(anEmployee.getEmployeeNumber()));
        jTextField1.setText(anEmployee.getFirstName());
        jTextField2.setText(anEmployee.getLastName());
        if (anEmployee.getSex() == 0) {
            jRadioButton4.doClick();
        }
        if (anEmployee.getSex() == 1) {
            jRadioButton5.doClick();
        }
        if (anEmployee.getSex() == 2) {
            jRadioButton6.doClick();
        }
        jComboBox1.setSelectedIndex(anEmployee.getWorkLocation());
        
        jFrame4.dispose();
        
        editMode = true; //Preparing the mainframe to edit an employee
        genericEmployee = anEmployee;
        jButton1.setText("Edit");
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here: prepares the search display and fills it  
        if (theEmployeeDatabase.searchTable(Integer.parseInt(jTextField9.getText())) != null) {
            jButton13.setVisible(true);
            jButton7.setVisible(true);
            jPanel9.setVisible(true);
            jButton14.setVisible(true);
            jFrame4.setVisible(true);
            
            EmployeeInfo anEmployee = theEmployeeDatabase.searchTable(Integer.parseInt(jTextField9.getText()));
            if (anEmployee instanceof my.employeedatabase.FullTimeEmployee) {
                FullTimeEmployee eFull = (FullTimeEmployee) anEmployee;
                jTextPane6.setText("Part Time");
                jTextPane7.setText(Double.toString(eFull.calcAnnualGrossIncome()));
                jTextPane8.setText(Double.toString(eFull.calcAnnualNetIncome()));
            } else if (anEmployee instanceof my.employeedatabase.PartTimeEmployee) {
                PartTimeEmployee ePart = (PartTimeEmployee) anEmployee;
                jTextPane6.setText("Full Time");
                jTextPane7.setText(Double.toString(ePart.calcAnnualGrossIncome()));
                jTextPane8.setText(Double.toString(ePart.calcAnnualNetIncome()));
            }

            jTextPane2.setText(anEmployee.getFirstName() + " " + anEmployee.getLastName());
            jTextPane3.setText(Integer.toString(anEmployee.getEmployeeNumber()));
            if (anEmployee.getSex() == 0) {
                jTextPane4.setText("Male");
            } else if (anEmployee.getSex() == 1) {
                jTextPane4.setText("Female");
            } else if (anEmployee.getSex() == 2) {
                jTextPane4.setText("Non-Binary");
            }
            if (anEmployee.getWorkLocation() == 0) {
                jTextPane5.setText("Mississauga");
            } else if (anEmployee.getWorkLocation() == 1) {
                jTextPane5.setText("Toronto");
            } else if (anEmployee.getWorkLocation() == 2) {
                jTextPane5.setText("Ottawa");
            }
        } else {
            //INSERT ERROR MESSAGE HERE!!!
        }
        jFrame3.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        jDialog1.dispose();
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        int selectedNumber = (int) jTable1.getValueAt(jTable1.getSelectedRow(),0);
        EmployeeInfo selectedEmployee = theEmployeeDatabase.searchTable(selectedNumber);
        
        if (selectedEmployee instanceof my.employeedatabase.FullTimeEmployee) {
            jPanel6.setVisible(false);
            jPanel5.setVisible(true);
            FullTimeEmployee eFull = (FullTimeEmployee) selectedEmployee;
            jTextPane6.setText("Part Time");
            jTextPane7.setText(Double.toString(eFull.calcAnnualGrossIncome()));
            jTextPane8.setText(Double.toString(eFull.calcAnnualNetIncome()));

            jTextField4.setText(Double.toString(eFull.getYearlySalary()));
            jTextField5.setText(Double.toString(eFull.getDeductionsRate()));
        } else if (selectedEmployee instanceof my.employeedatabase.PartTimeEmployee) {
            jPanel5.setVisible(false);
            jPanel6.setVisible(true);
            PartTimeEmployee ePart = (PartTimeEmployee) selectedEmployee;
            jTextPane6.setText("Full Time");
            jTextPane7.setText(Double.toString(ePart.calcAnnualGrossIncome()));
            jTextPane8.setText(Double.toString(ePart.calcAnnualNetIncome()));

            jTextField6.setText(Double.toString(ePart.getHourlyWage()));
            jTextField7.setText(Double.toString(ePart.getHoursPerWeek()));
            jTextField8.setText(Double.toString(ePart.getWeeksPerYear()));
            jTextField10.setText(Double.toString(ePart.getDeductionsRate()));
        }

        jTextPane2.setText(selectedEmployee.getFirstName() + " " + selectedEmployee.getLastName());
        jTextPane3.setText(Integer.toString(selectedEmployee.getEmployeeNumber()));
        if (selectedEmployee.getSex() == 0) {
            jTextPane4.setText("Male");
        } else if (selectedEmployee.getSex() == 1) {
            jTextPane4.setText("Female");
        } else if (selectedEmployee.getSex() == 2) {
            jTextPane4.setText("Non-Binary");
        }
        if (selectedEmployee.getWorkLocation() == 0) {
            jTextPane5.setText("Mississauga");
        } else if (selectedEmployee.getWorkLocation() == 1) {
            jTextPane5.setText("Toronto");
        } else if (selectedEmployee.getWorkLocation() == 2) {
            jTextPane5.setText("Ottawa");
        }

        jTextField3.setText(Integer.toString(selectedEmployee.getEmployeeNumber()));
        jTextField1.setText(selectedEmployee.getFirstName());
        jTextField2.setText(selectedEmployee.getLastName());
        if (selectedEmployee.getSex() == 0) {
            jRadioButton4.doClick();
        }
        if (selectedEmployee.getSex() == 1) {
            jRadioButton5.doClick();
        }
        if (selectedEmployee.getSex() == 2) {
            jRadioButton6.doClick();
        }
        jComboBox1.setSelectedIndex(selectedEmployee.getWorkLocation());
        jFrame1.dispose(); //Closing the table window
        
        editMode = true; //Preparing the mainframe to edit an employee
        genericEmployee = selectedEmployee;
        jButton1.setText("Edit");
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
        int selectedNumber = (int) jTable1.getValueAt(jTable1.getSelectedRow(),0);
        EmployeeInfo removedEmployee = theEmployeeDatabase.removeFromTable(selectedNumber);
        String msg = "";
        if (removedEmployee != null){
            msg = "The employee with employee number \"" + removedEmployee.getEmployeeNumber() + "\" was removed from our database";
        } else if (removedEmployee == null){
            msg = "The employee does not exist in our database";
        }
        
        ArrayList<EmployeeInfo> employeeList = theEmployeeDatabase.retrieveTable();

        //Update Table
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        tModel.setRowCount(employeeList.size());
        jTable1.setModel(tModel);
        for (int i = 0; i < employeeList.size(); i++) {
            jTable1.setValueAt(employeeList.get(i).getEmployeeNumber(), i, 0);
            jTable1.setValueAt(employeeList.get(i).getFirstName(), i, 1);
            jTable1.setValueAt(employeeList.get(i).getLastName(), i, 2);
            if (employeeList.get(i) instanceof my.employeedatabase.FullTimeEmployee) {
                jTable1.setValueAt("Full Time", i, 3);
            } else if (employeeList.get(i) instanceof my.employeedatabase.PartTimeEmployee) {
                jTable1.setValueAt("Part Time", i, 3);
            }
        }
        if (employeeList.size() < 8);
        jTable1.setSize(new Dimension(300, 128 - (8 - employeeList.size()) * 16));
        jFrame1.pack();
        jButton12.setVisible(false);
        jButton15.setVisible(false);
        
        jLabel17.setText(msg);
        jDialog1.pack();
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        // TODO add your handling code here:
        jFrame1.dispose();
    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        // TODO add your handling code here:
        jFrame3.dispose();
    }//GEN-LAST:event_jButton17MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != 1){
            jButton12.setVisible(true);
            jButton15.setVisible(true);
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
        // TODO add your handling code here:
        System.out.println("kys");
    }//GEN-LAST:event_jTextField9KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabaseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabaseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabaseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabaseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDatabaseUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane jTextPane8;
    // End of variables declaration//GEN-END:variables
}
